source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target '${POD_NAME}_Demo', :exclusive => true do
  pod '${POD_NAME}', :path => '.'
end

target '${POD_NAME}_Tests', :exclusive => true do
  pod '${POD_NAME}', :path => '.'

  ${INCLUDED_PODS}
end
